### ISSUE TITLE
The latest commit triggers an ReferenceError

### ISSUE THREAD

**Issue by OceanLin** [pierrec/node-eval#22]
The latest commit (https://github.com/pierrec/node-eval/commit/527557aa29cff8ab0993dc2351ba3520631b6528) add a line of code "sandbox.URL = URL", however URL is not defined before.

I use the plugin "static-site-generator-webpack-plugin" which uses your package in their code and I got the error today when I built my package.

ERROR in ReferenceError: URL is not defined
    at module.exports (/home/circleci/repo/web_static/node_modules/eval/eval.js:59:17)

**Comment by Liammarwood** [comment]
This has happened with my project too, quick fix is to have the eval: "0.1.4" in the package.json
