### ISSUE TITLE
ReferenceError: __webpack_require__ is not defined

### ISSUE THREAD

**Issue by LekoArts** [pierrec/node-eval#29]
Hi!

We've been debugging the issue https://github.com/seek-oss/vanilla-extract/issues/637 over at the vanilla-extract repository and it seems that the recent 0.1.7 version introduced a regression causing webpack to fail.

For now this is "fixed" by pinning to an older version: https://github.com/seek-oss/vanilla-extract/pull/639

Thanks for creating and maintaining this library!

**Comment by Josh-Cena** [comment]
Hi, should be fixed by #28. My bad!
