### ISSUE TITLE
includeGlobals is not true by default

### ISSUE THREAD

**Issue by Zacqary** [pierrec/node-eval#5]
Is this a mistake in the readme or a mistake in the code?

**Comment by markdalgleish** [comment]
Came here to raise the exact same issue. Happy to send a PR to fix the code or documentation, I just don't know which is correct.

**Comment by pierrec** [comment]
It should be false by default. The README is wrong.
I dont have access to git right now, if you could pull in a fix, it would be much appreciated! :)
