### ISSUE TITLE
Default for `includeGlobals` is not true.

### ISSUE THREAD

**Issue by reggi** [pierrec/node-eval#7]

**Comment by pierrec** [comment]
Hello,

Indeed includeGlobals is false by default.
The documentation was fixed accordingly.
Is this your issue?

**Comment by reggi** [comment]
Hey, I got it working, I had to provide empty object and true.

https://github.com/reggi/evalmd/blob/master/test-markdown.js#L58

**Comment by pierrec** [comment]
Ok.
